#!/bin/bash

# Blow away Cake UI node modules to prevent conflict.
if [ -d "./third_party/cake_ui/node_modules" ]; then
  rm -rf ./third_party/cake_ui/node_modules
fi

# Blow away Cake New Tab node modules to prevent conflict.
if [ -d "./chrome/browser/resources/cake_new_tab/node_modules" ]; then
  rm -rf ./chrome/browser/resources/cake_new_tab/node_modules
fi

autoninja -C out/release chrome